# This source file is part of the Ook project (2024), which is released under
# the The GNU General Public License v3.0. You can find the license text here:
#
# 	https://www.gnu.org/licenses/gpl-3.0-standalone.html
#
# Defines a program.

include share/mk/ook.cc.mk

# Pick our linker based on what languages this program is made of.
ifneq ($(strip $(filter %.cpp,$($(UNIQ)_SOURCES))),)
	$(UNIQ)_LINKER = $(XCPP)
else
	$(UNIQ)_LINKER = $(XCC)
endif

include share/mk/ook.dep.mk
include share/mk/ook.artifact.mk

TARGET_LIST += $($(UNIQ)_BUILD_DIR)/$(NAME) $(UNIQ)

$(UNIQ): $($(UNIQ)_BUILD_DIR)/$(NAME)

$($(UNIQ)_BUILD_DIR)/$(NAME): override UNIQ := $(UNIQ)
$($(UNIQ)_BUILD_DIR)/$(NAME): $($(UNIQ)_OBJS) $($(UNIQ)_DEPS)
	$(SAY) "LD" $(ROOT_SOURCE_DIR_ABS)/$@
	$(V)mkdir -p $(dir $@)
	$(V)$(strip $($(UNIQ)_LINKER) -o $@ $(LDFLAGS) $($(UNIQ)_LDFLAGS) \
	   -ffreestanding -nostdlib -T sys/arch/$(ARCH)/kernel.ld \
	    $($(UNIQ)_OBJS)) \
		$($(UNIQ)_LINKS_AGAINST)

# Include all the dependency files generated by the compiler.
$(eval -include $($(UNIQ)_DEPFILES))
