name: Promote Mailing List (PR)

on:
    pull_request:
        types:
            - opened

jobs:
    auto-reply:
        runs-on: ubuntu-latest
        steps:
            - name: Skip if PR author is milobanks
              id: check_author
              run: |
                  if [[ "${{ github.event.pull_request.user.login }}" == "milobanks" ]]; then
                    echo "Skipping because author is milobanks."
                    echo "skip_reply=true" >> $GITHUB_ENV
                  fi

            - name: Comment on new pull request
              if: env.skip_reply != 'true'
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.PAT }}
                  script: |
                      const repo = context.repo.repo;
                      const pr_number = context.payload.pull_request.number;
                      const message = `Thanks for the pull request! I don't merge PRs directly into GitHub, but we can discuss it here, and then I can create and apply the patch myself.

                      If you'd prefer, you can also send patches via the mailing list at https://lists.sr.ht/~milobanks/${repo}.`;

                      await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: pr_number,
                        body: message
                      });
